name = "HypergraphSignals"
uuid = "c115e4b6-f67f-469c-90f0-6e8e9b5d57d9"
version = "0.1.0"
authors = ["David Hong <hong@udel.edu>, Isabel Cano <isabelc@udel.edu>, and contributors"]

[workspace]
projects = ["test"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"

[compat]
Combinatorics = "1.1.0"
FFTW = "1.10.0"
LinearAlgebra = "1.12.0"
NPZ = "0.4.3"
julia = "1.10"
